# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'firstAlamofire' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for firstAlamofire
  pod 'Alamofire', '~> 5.6'

end
