# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'CollectionViewAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  

  # Pods for CollectionViewAPI
pod 'Alamofire', '~> 5.6'
pod 'SwiftyJSON', '~> 5.0'

end
